name: "Static Analysis"

on:
  pull_request:
    branches:
      - "*.x"
    paths:
      - composer.*
      - psalm*
      - src/**
      - tests/**

  push:
    branches:
      - "*.x"
    paths:
      - composer.*
      - psalm*
      - src/**
      - tests/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: '8.2'
      - name: Install dependencies
        uses: ramsey/composer-install@v3

      - name: Static Analysis
        run: "composer run static-analysis"
